### ISSUE TITLE
'module' object has no attribute 'NextPageField'

### ISSUE THREAD

**Issue by dvalp** [smartercleanup/api#29]
We are now getting an error when calling pagination.NextPageField(source='*') on the rest_framework.pagination module: AttributeError: 'module' object has no attribute 'NextPageField'

**Comment by LukeSwart** [comment]
I think I have a fix for this in the works, but it's not ready. Basically, I am renaming the `pagination_serializer_class` to `pagination_class` because `pagination_serializer_class` is deprecated, as listed here: http://www.django-rest-framework.org/topics/3.1-announcement/ and `pagination_class` can be found here: http://www.django-rest-framework.org/api-guide/pagination/#example (just do a search for `pagination_class` on that page).

You can also see how pagination works when we load lots of places, like in this example here: https://raingardens-api.heyduwamish.org/api/v2/smartercleanup/datasets/raingardens/places where we have the `metadata` key like this:

```
    "metadata": {
        "length": 3090, 
        "next": "http://raingardens-api.heyduwamish.org/api/v2/smartercleanup/datasets/raingardens/places?page=2", 
        "previous": null, 
        "page": 1, 
        "num_pages": 7
    }, 
```

The implementation for the `next` and `previous` keys has changed, because it is built into the `pagination.PageNumberPagination` class instead of implementing it ourselves: http://www.django-rest-framework.org/api-guide/pagination/#pagenumberpagination 

I'm not really sure yet, but I think we can do something along these lines in our `serializers.py`:

```
# # class PaginationMetadataSerializer (serializers.Serializer):
# class PaginationMetadataSerializer (pagination.PageNumberPagination):
#     # length = serializers.Field(source='paginator.count')
#     # next = pagination.NextPageField(source='*')
#     # previous = pagination.PreviousPageField(source='*')
#     # page = serializers.Field(source='number')
#     # num_pages = serializers.Field(source='paginator.num_pages')

#     # length = serializers.Field(source='paginator.count')
#     page = serializers.Field(source='number')
#     num_pages = serializers.Field(source='paginator.num_pages')

#     # 'paginate_by_param' will be deprecated from global settings,
#     # so we are using it here instead:
#     paginate_by_param = 'page_size'


# class PaginatedResultsSerializer (pagination.BasePaginationSerializer):
class PaginatedResultsSerializer (pagination.PageNumberPagination):
    # metadata = PaginationMetadataSerializer(source='*')
    many = True

```

And then make this change in our `base_views.py`:

```
    serializer_class = serializers.PlaceSerializer
    # pagination_serializer_class = serializers.FeatureCollectionSerializer
```

I am probably missing some things, but that is my current progress on this issue. Looking at the `pagination.py` class for the Django framework also helps, under here for example: `~/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/rest_framework/pagination.py` and docs here: https://docs.djangoproject.com/en/1.8/topics/pagination/

**Comment by LukeSwart** [comment]
I think I resolved this error on this commit: https://github.com/smartercleanup/api/pull/31/commits/dc41db45c3cd5f5437ce0d84044d397fecb04be6

Now we are getting a new error:

```
Traceback (most recent call last):
  File "./manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/lucas/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/lucas/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/lucas/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/lucas/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/lucas/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/lucas/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/lucas/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/lucas/projects/SmarterCleanup/smartercleanup-api/src/sa_api_v2/admin.py", line 22, in <module>
    from .tasks import clone_related_dataset_data
  File "/home/lucas/projects/SmarterCleanup/smartercleanup-api/src/sa_api_v2/tasks.py", line 14, in <module>
    from .renderers import CSVRenderer, JSONRenderer, GeoJSONRenderer
  File "/home/lucas/projects/SmarterCleanup/smartercleanup-api/src/sa_api_v2/renderers.py", line 2, in <module>
    from rest_framework.renderers import JSONRenderer, JSONPRenderer
ImportError: cannot import name JSONPRenderer
```

It looks like `JSONPRenderer` has been deprecated? I'll make an issue and look into it, but let me know if you find out anything interesting!

**Comment by LukeSwart** [comment]
I was able to work around the JSONP situation by using the `djangorestframework-jsonp` renderer mentioned above. See this commit for details: https://github.com/smartercleanup/api/pull/31/commits/35b30892949eeb55482f242479dcc0503f24b5ea

Good news is that the server is now running, but now we need to fix our unit tests and other errors.
