### ISSUE TITLE
'module' object has no attribute 'OAuth2Authentication'

### ISSUE THREAD

**Issue by dvalp** [smartercleanup/api#34]
Multiple tests failing with:
AttributeError: 'module' object has no attribute 'OAuth2Authentication'

**Comment by LukeSwart** [comment]
I'm looking into this now, and it seems like this error is related to using `django-oauth-toolkit` instead of `django-auth2-provider` 

Here are the DRF docs with respect to `django-auth2-provider:
http://www.tomchristie.com/rest-framework-2-docs/api-guide/authentication#oauth2authentication

And the docs for using our new `django-oauth-toolkit`module with DRF:
http://www.django-rest-framework.org/api-guide/authentication/#django-oauth-toolkit

**Comment by LukeSwart** [comment]
Fixed in PR #36, or more specifically, in the commits referenced above (ie 8df569f)
